Refactoring for more compatible among various OSs

diff --git a/UTL/base64 b/UTL/base64
--- a/UTL/base64
+++ b/UTL/base64
@@ -18,7 +18,7 @@
 #                       from wrapping.
 #        -i ........... When decoding, ignore non-alphabet characters.
 #
-# Written by Shell-Shoccar Japan (@shellshoccarjpn) on 2017-03-05
+# Written by Shell-Shoccar Japan (@shellshoccarjpn) on 20202017-05-02
 #
 # This is a public-domain software (CC0). It means that all of the
 # people can use this for any purposes with no restrictions at all.
@@ -36,7 +36,8 @@
 set -u
 umask 0022
 export LC_ALL=C
-export PATH="$(command -p getconf PATH)${PATH:+:}${PATH:-}"
+export PATH="$(command -p getconf PATH)${PATH+:}${PATH-}"
+export UNIX_STD=2003  # to make HP-UX conform to POSIX
 
 # === Define the functions for printing usage and error message ======
 print_usage_and_exit () {
@@ -48,7 +49,7 @@ print_usage_and_exit () {
 	            -d, -w <COLS>, -i
 	          But --by-myself is the only original option, it prevent
 	          from use the built-in same name command even if available
-	Version : 2017-03-05 04:49:02 JST
+	Version : 20202017-05-02 21:11:01 JST
 	          (POSIX Bourne Shell/POSIX commands)
 	            * Although the bult-in base64, uuencode and uudecode command or
 	              GNU AWK produces better performance than the POSIX commands set
@@ -68,9 +69,9 @@ error_exit() {
 # === FUNC: which command also works on Just a POSIX environment =====
 which which >/dev/null 2>&1 || {
   which() {
-    command -v "$1" 2>/dev/null |
-    awk 'match($0,/^\//){print; ok=1;}
-         END {if(ok==0){print "which: not found" > "/dev/stderr"; exit 1}}'
+    command -v "$1" 2>/dev/null | grep '^/' || {
+      echo 'which: not found' 1>&2 && (exit 1)
+    }
   }
 }
 
@@ -89,7 +90,7 @@ esac
 #
 # --- use "bult-in" base64 if available and wanted -------------------
 if   [ $by_myself -eq 0 ] && printf 1 | base64 -w 0 >/dev/null 2>&1; then
-  exec base64 "$@"
+  exec base64 ${1+"$@"}
   exit 1
 elif [ $by_myself -eq 0 ] && printf 1 | base64 -b 0 >/dev/null 2>&1; then
   # If Mac OS X version exists, I will use it after option parsing
@@ -203,12 +204,22 @@ case $# in
   1) file=$1             ;;
   *) print_usage_and_exit;;
 esac
-case "$file" in
-  /*) :             ;;
-   -) :             ;;
-  '') file='-'      ;;
-   *) file="./$file";;
-esac
+
+# === Validate the arguments =========================================
+if   [ "_$file" = '_'                ] ||
+     [ "_$file" = '_-'               ] ||
+     [ "_$file" = '_/dev/stdin'      ] ||
+     [ "_$file" = '_/dev/fd/0'       ] ||
+     [ "_$file" = '_/proc/self/fd/0' ]  ; then
+  file=''
+elif [ -f "$file"                    ] ||
+     [ -c "$file"                    ] ||
+     [ -p "$file"                    ]  ; then
+  [ -r "$file" ] || error_exit 1 'Cannot open the file: '"$file"
+else
+  print_usage_and_exit
+fi
+case "$file" in ''|-|/*|./*|../*) :;; *) file="./$file";; esac
 
 
 ######################################################################
@@ -220,7 +231,7 @@ case "$by_myself${CMD_BASE64_MAC:-}" in 0/*)
   opts=''
   case $mode in d) opts="$opts -d";; esac
   opts="$opts -b $width"
-  exec "$CMD_BASE64_MAC" $opts -i "$file"
+  exec "$CMD_BASE64_MAC" $opts -i ${file:+"$file"}
   exit 1
   ;;
 esac
@@ -229,12 +240,12 @@ esac
 if [ $by_myself -eq 0 ] && uuencode -m dummy </dev/null >/dev/null 2>&1; then
   case "$mode" in
     d) [ -w /dev/stdout ] && {
-         (echo 'begin-base64 644 dummy'; cat "$file"; echo '====') |
+         (echo 'begin-base64 644 dummy'; cat ${file:+"$file"}; echo '====') |
          uudecode -o /dev/stdout
          exit $?
        }
        ;;
-    e) cat "$file"                                  |
+    e) cat ${file:+"$file"}                         |
        uuencode -m dummy                            |
        sed '1d;$d'                                  |
        case $width in                               #
@@ -249,7 +260,7 @@ fi
 
 # === Encode/Decode by myself ========================================
 case $mode$binarable_awk in
-  e*) cat "$file"                                                              |
+  e*) cat ${file:+"$file"}                                                     |
       od -A n -t x1 -v                                                         |
       tr -Cd '0123456789abcdefABCDEF\n'                                        |
       awk 'BEGIN{OFS=""; ORS="";                                               #
@@ -305,10 +316,7 @@ case $mode$binarable_awk in
         '')     max1line=4096           ;;
         [0-9]*) max1line=$((max1line/2));;
       esac
-      case "$file" in                                                         #
-        -) fold -b -w 508        ;;                                           #
-        *) fold -b -w 508 "$file";;                                           #
-      esac                                                                    |
+      fold -b -w 508 ${file:+"$file"}                                         |
       case $opti in                                                           #
         1) sed 's![^A-Za-z0-9+/=]!!g';;                                       #
         *) cat                       ;;                                       #
@@ -413,10 +421,7 @@ case $mode$binarable_awk in
       # <LF>   :  "\\\\n"     \\n         \n          <LF>                 #
       # "      :  "\\\""      \"          "           "                    #"
       # '      :  "\\'"'"'"   \'          '           '                    #'
-  d1) case "$file" in                                                         #
-        -) fold -b -w 508        ;;                                           #
-        *) fold -b -w 508 "$file";;                                           #
-      esac                                                                    |
+  d1) fold -b -w 508 ${file:+"$file"}                                         |
       case $opti in                                                           #
         1) sed 's![^A-Za-z0-9+/=]!!g';;                                       #
         *) cat                       ;;                                       #
diff --git a/UTL/mime-make b/UTL/mime-make
--- a/UTL/mime-make
+++ b/UTL/mime-make
@@ -41,7 +41,7 @@
 # Return: $?=0 (when all of the arguments are valid)
 #         stdout : generated MIME formatted data
 #
-# Written by Shell-Shoccar Japan (@shellshoccarjpn) on 2017-04-04
+# Written by Shell-Shoccar Japan (@shellshoccarjpn) on 20202017-05-02
 #
 # This is a public-domain software (CC0). It means that all of the
 # people can use this for any purposes with no restrictions at all.
@@ -58,7 +58,8 @@
 # === Initialize shell environment ===================================
 set -u
 export LC_ALL=C
-export PATH="$(command -p getconf PATH)${PATH:+:}${PATH:-}"
+export PATH="$(command -p getconf PATH)${PATH+:}${PATH-}"
+export UNIX_STD=2003  # to make HP-UX conform to POSIX
 
 # === Define the functions for printing usage ========================
 print_usage_and_exit () {
@@ -96,7 +97,7 @@ print_usage_and_exit () {
 	                (default is --crlf when form-mode, --lf when mail-mode)
 	  --b64/--raw : switch about applying or not Base64 to the <file> of (c)-(f)
 	                (default is --raw)
-	Version : 2017-04-04 14:20:51 JST
+	Version : 20202017-05-02 21:11:01 JST
 	          (POSIX Bourne Shell/POSIX commands)
 	USAGE
   exit 1
@@ -120,9 +121,9 @@ LFs=$(printf '\n_'); LFs=${LFs%_} # Use as a "\n" in s-command of sed
 # === which command also works on Just a POSIX environment ($1:command name)
 which which >/dev/null 2>&1 || {
   which() {
-    command -v "$1" 2>/dev/null |
-    awk 'match($0,/^\//){print; ok=1;}
-         END {if(ok==0){print "which: not found" > "/dev/stderr"; exit 1}}'
+    command -v "$1" 2>/dev/null | grep '^/' || {
+      echo 'which: not found' 1>&2 && (exit 1)
+    }
   }
 }
 
@@ -1122,9 +1123,9 @@ decide_type() {
 
 # === Validate and exit if the file is invalid =======================
 use_stdin=0
-validate_file() {
-  case $1 in
-    '-'|'/dev/stdin'|'/dev/fd/0'|'/dev/self/fd/0')
+validate_and_normalize_file_str() {
+  case "$file" in
+    ''|'-'|'/dev/stdin'|'/dev/fd/0'|'/dev/self/fd/0')
       use_stdin=$((use_stdin+1))
       case $use_stdin in
         [01]) return 0;;
@@ -1133,12 +1134,14 @@ validate_file() {
               exit 1
               ;;
       esac
+      file=''
       ;;
     *)
-      [ -f "$1" ] || [ -c "$1" ] || [ -p "$1" ] || {
-        printf '%s: Invalid file: %s\n' "${0##*/}" "$1" 1>&2
+      [ -f "$file" ] || [ -c "$file" ] || [ -p "$file" ] || {
+        printf '%s: Invalid file: %s\n' "${0##*/}" "$file" 1>&2
         exit 1
       }
+      case "$file" in /*|./*|../*) :;; *) file="./$file";; esac
       ;;
   esac
 }
@@ -1205,21 +1208,21 @@ while [ $# -gt 0 ]; do
     -Tf)  mode='textform'
           case $# in
             1) print_usage_and_exit;;
-            2) file='-'            ;;
+            2) file=''             ;;
             *) file=$3             ;;
           esac
-          validate_file "$file"
-          text=$(cat "$file")
+          validate_and_normalize_file_str
+          text=$(cat ${file:+"$file"})
           name=$2
           case $# in 2) shift 2;; *) shift 3;; esac
           ;;
     -F)   mode='fileform'
           case $# in
             1) print_usage_and_exit         ;;
-            2) file='-'                     ;;
+            2) file=''                      ;;
             *) file=$3; filename=${file##*/};;
           esac
-          validate_file "$file"
+          validate_and_normalize_file_str
           ext=${file##*/};case "${ext##*.}" in "$ext") ext='';; esac
           type=$(decide_type "${ext##*.}")
           name=$2
@@ -1228,10 +1231,10 @@ while [ $# -gt 0 ]; do
     -Ff)  mode='fileform'
           case $# in
             [12]) print_usage_and_exit;;
-               3) file='-'            ;;
+               3) file=''             ;;
                *) file=$4             ;;
           esac
-          validate_file "$file"
+          validate_and_normalize_file_str
           filename=$3
           ext=${file##*/};case "${ext##*.}" in "$ext") ext='';; esac
           type=$(decide_type "${ext##*.}")
@@ -1241,10 +1244,10 @@ while [ $# -gt 0 ]; do
     -Ft)  mode='fileform'
           case $# in
             [12]) print_usage_and_exit         ;;
-               3) file='-'                     ;;
+               3) file=''                      ;;
                *) file=$4; filename=${file##*/};;
           esac
-          validate_file "$file"
+          validate_and_normalize_file_str
           type=$3
           name=$2
           case $# in 3) shift 3;; *) shift 4;; esac
@@ -1252,10 +1255,10 @@ while [ $# -gt 0 ]; do
     -Ftf) mode='fileform'
           case $# in
             [123]) print_usage_and_exit;;
-                4) file='-'            ;;
+                4) file=''             ;;
                 *) file=$5             ;;
           esac
-          validate_file "$file"
+          validate_and_normalize_file_str
           filename=$4
           type=$3
           name=$2
@@ -1263,19 +1266,19 @@ while [ $# -gt 0 ]; do
           ;;
     -M)   mode='mailbody'
           case $# in
-            1) file='-'            ;;
+            1) file=''             ;;
             *) file=$2             ;;
           esac
-          validate_file "$file"
+          validate_and_normalize_file_str
           case $# in 1) shift  ;; *) shift 2;; esac
           ;;
     -A)   mode='mailatch'
           case $# in
-            1) file='-'                     ;;
+            1) file=''                      ;;
             *) file=$2; filename=${file##*/};;
           esac
           name=$filename
-          validate_file "$file"
+          validate_and_normalize_file_str
           ext=${file##*/};case "${ext##*.}" in "$ext") ext='';; esac
           type=$(decide_type "${ext##*.}")
           case $# in 1) shift 1;; *) shift 2;; esac
@@ -1283,10 +1286,10 @@ while [ $# -gt 0 ]; do
     -Af)  mode='mailatch'
           case $# in
             1) print_usage_and_exit;;
-            2) file='-'            ;;
+            2) file=''             ;;
             *) file=$3             ;;
           esac
-          validate_file "$file"
+          validate_and_normalize_file_str
           filename=$2
           name=$filename
           ext=${file##*/};case "${ext##*.}" in "$ext") ext='';; esac
@@ -1296,10 +1299,10 @@ while [ $# -gt 0 ]; do
     -At)  mode='mailatch'
           case $# in
             1) print_usage_and_exit         ;;
-            2) file='-'                     ;;
+            2) file=''                      ;;
             *) file=$3; filename=${file##*/};;
           esac
-          validate_file "$file"
+          validate_and_normalize_file_str
           name=$filename
           type=$2
           case $# in 2) shift 2;; *) shift 3;; esac
@@ -1307,10 +1310,10 @@ while [ $# -gt 0 ]; do
     -Atf) mode='mailatch'
           case $# in
             [12]) print_usage_and_exit;;
-               3) file='-'            ;;
+               3) file=''             ;;
                *) file=$4             ;;
           esac
-          validate_file "$file"
+          validate_and_normalize_file_str
           filename=$3
           name=$filename
           type=$2
@@ -1352,8 +1355,8 @@ while [ $# -gt 0 ]; do
                 esac
                 printf '%s\n' "$cr"
                 case "$base64" in
-                   0) cat "$file"           ;;
-                   *) cat "$file"           |
+                   0) cat ${file:+"$file"}  ;;
+                   *) cat ${file:+"$file"}  |
                       base64 --wrap=76      |
                       sed '$!s/$/@ /'       |
                       tr -d '\n'            |
@@ -1371,7 +1374,7 @@ while [ $# -gt 0 ]; do
                        "$cr"
                 printf 'Content-Type: text/plain; charset="UTF-8"%s\n%s\n' \
                        "$cr" "$cr"
-                grep ^ "$file"            | # For the mailbody text,
+                grep '' ${file:+"$file"}  | # For the mailbody text,
                 sed "/^\$/s/\$/$CR/"      | # it must be always put <CR>
                 sed "/[^$CR]\$/s/\$/$CR/" | # on the end of every line
                 base64 --wrap=76          |
@@ -1391,7 +1394,7 @@ while [ $# -gt 0 ]; do
                        "$cr"
                 printf 'Content-Type: %s; name="%s"%s\n%s\n'                \
                        "$type" "$name" "$cr" "$cr"
-                cat "$file"           |
+                cat ${file:+"$file"}  |
                 base64 --wrap=76      |
                 sed '$!s/$/@ /'       |
                 tr -d '\n'            |
diff --git a/UTL/sendjpmail b/UTL/sendjpmail
--- a/UTL/sendjpmail
+++ b/UTL/sendjpmail
@@ -23,7 +23,7 @@
 #   * If the following headers is omitted, inserted by this function.
 #     "Content-Type:", "Content-Transfer-Encoding:", "MIME-Version:"
 #
-# Written by Shell-Shoccar Japan (@shellshoccarjpn) on 2017-04-04
+# Written by Shell-Shoccar Japan (@shellshoccarjpn) on 2020202017-05-02
 #
 # This is a public-domain software (CC0). It means that all of the
 # people can use this for any purposes with no restrictions at all.
@@ -41,16 +41,17 @@
 set -u
 umask 0022
 export LC_ALL=C
-PATH="/usr/sbin:/sbin:/usr/local/sbin${PATH:+:}${PATH:-}"
+PATH="/usr/sbin:/sbin:/usr/local/sbin${PATH+:}${PATH-}"
 PATH="$(command -p getconf PATH):$PATH"
 export PATH
+export UNIX_STD=2003  # to make HP-UX conform to POSIX
 
 # === Usage printing function ========================================
 print_usage_and_exit () {
   cat <<-USAGE 1>&2
 	Usage   : ${0##*/} <mailfile>
 	Args    : <mailfile> ... Text data as a e-mail
-	Version : 2017-04-04 16:04:09 JST
+	Version : 2020202017-05-02 21:11:01 JST
 	          (POSIX Bourne Shell/POSIX commands/sendmail command/UTF-8)
 	USAGE
   exit 1
@@ -71,9 +72,9 @@ TAB=$(printf '\t'   )
 # === FUNC : which command also works on Just a POSIX env. ($1:command name)
 which which >/dev/null 2>&1 || {
   which() {
-    command -v "$1" 2>/dev/null |
-    awk 'match($0,/^\//){print; ok=1;}
-         END {if(ok==0){print "which: not found" > "/dev/stderr"; exit 1}}'
+    command -v "$1" 2>/dev/null | grep '^/' || {
+      echo 'which: not found' 1>&2 && (exit 1)
+    }
   }
 }
 
@@ -202,22 +203,34 @@ esac
 # Parse Arguments
 ######################################################################
 
-# === Parse Filename Given as an Argument ============================
+# === Get the options and the filepath ===============================
+# --- initialize option parameters -----------------------------------
 file=''
+#
+# --- get them -------------------------------------------------------
 case $# in
-     0) file='-'
-        ;;
-  [12]) [ -f "$1" ] || [ -c "$1" ] || [ -p "$1" ] || [  "_$1" = '_-' ] || {
-          print_usage_and_exit
-        }
-        file=$1
-        case "$file" in -|/*|./*|../*) :;; *) file="./$file";; esac
-        ;;
+     0) :                   ;;
+  [12]) file=$1             ;;
         # supporting $#==2 is for compatibility with the previous version
         # even if given, ignored
-     *) print_usage_and_exit
-        ;;
+     *) print_usage_and_exit;;
 esac
+
+# === Validate the arguments =========================================
+if   [ "_$file" = '_'                ] ||
+     [ "_$file" = '_-'               ] ||
+     [ "_$file" = '_/dev/stdin'      ] ||
+     [ "_$file" = '_/dev/fd/0'       ] ||
+     [ "_$file" = '_/proc/self/fd/0' ]  ; then
+  file=''
+elif [ -f "$file"                    ] ||
+     [ -c "$file"                    ] ||
+     [ -p "$file"                    ]  ; then
+  [ -r "$file" ] || error_exit 1 'Cannot open the file: '"$file"
+else
+  print_usage_and_exit
+fi
+case "$file" in ''|-|/*|./*|../*) :;; *) file="./$file";; esac
 
 
 ######################################################################
@@ -232,7 +245,7 @@ mv=0   # be set to 1 if the mail text has "MIME-Version:" header
 IFS='
 '
 mode=''
-cat "$file"                                                                    |
+cat ${file:+"$file"}                                                           |
 while read -r line; do                                                         #
   case "$line" in                                                              #
     '')                                mode='endh'               ;;            #
@@ -287,7 +300,7 @@ while read -r line; do                                                         #
       sed "/^ESC:/s/;/$NAK/g"                                    |             #
       sed 's/^....//'                                            |             #
       tr '\n' '"'                                                |             #
-      grep ^                                                     |             #
+      grep ''                                                    |             #
       sed 's/"$//'                                               |             #
       sed "s/\\([,;]\\)/\\1$LFs/g"                               |             #
       sed 's/^['"$TAB"' ]\{1,\}//'                               |             #
@@ -305,12 +318,12 @@ while read -r line; do                                                         #
         while read -r str2; do                           #                     #
           printf '%s' "${str2}" |                        #                     #
           base64 --wrap=0       |                        #                     #
-          grep ^                                         #                     #
+          grep ''                                        #                     #
         done                                             |                     #
         sed 's/.*/=?UTF-8?B?&?=/'                        |                     #
         sed '1!s/^/'"$TAB"'/'                            |                     #
         tr '\n' "$ACK"                                   |                     #
-        grep ^                                           |                     #
+        grep ''                                          |                     #
         sed "s/$ACK\$//"                                 |                     #
         tr -d '\n'                                       |                     #
         tr "$ACK" '\n'                                                         #
@@ -339,7 +352,7 @@ while read -r line; do                                                         #
       echo                                                                     #
       # 3) print the body part                                                 #
       case "$((cte+ct_m))" in                                                  #
-        0) grep ^                    | # For the mailbody text,                #
+        0) grep ''                   | # For the mailbody text,                #
            sed "/^\$/s/\$/$CR/"      | # it must be always put <CR>            #
            sed "/[^$CR]\$/s/\$/$CR/" | # on the end of every line              #
            base64 --wrap=76         ;;                                         #
